backend:
  name: git-gateway
  branch: main


media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "paintings"
    label: "Paintings"
    folder: "content/paintings"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "image", label: "Image", widget: "image" }
