backend:
  name: github
  repo: FoxAbstractArtist/foxpaintings
  branch: main
  auth_scope: repo
  base_url: https://api.netlify.com
  auth_endpoint: oauth2/authorize
  client_id: Ov23cttx6UWJAOcHffld

media_folder: "images/uploads" # path inside repo
public_folder: "/images/uploads" # path in website

collections:
  - name: "paintings"
    label: "Paintings"
    label_singular: "Painting"
    folder: "content/paintings"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
