backend:
  name: git-gateway
  branch: main # your default branch

media_folder: "src/paintings/content/images/uploads"
public_folder: "/paintings/content/images/uploads"

collections:
  - name: "paintings"
    label: "Paintings"
    folder: "src/paintings"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
