backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "paintings"
    label: "Paintings"
    folder: "src/paintings"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Size", name: "size", widget: "string", required: false }
      - { label: "Medium", name: "medium", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image" }
